### ISSUE TITLE
Activate scope in EARs

### ISSUE THREAD

**Issue by heruan** [tomitribe/microscoped#5]
Given an EAR with two WARs, how can I activate a scope from a WAR? For example, given a new `TenantScoped` context, a bean `@TenantScoped TenantResolver` is defined in the EAR; in a WAR, a `RequestScoped` should activate the `TenantResolver` in the EAR.

I tried this, but it seems the `BeanManager` in the WAR is isolated from the EAR, thus throwing "Scope not active" when trying to get a `TenantResolver` instance:

```java
@RequestScoped
public class TenantActivator {

    @Inject
    BeanManager bm;

    public void activateTenant(String tenant) {
        ScopeContext<String> content = (ScopeContext<String>) bm.getContext(TenantScoped.class);
        context.enter(tenant);
    }

}
```

but when the EAR tries to get something which is `@TenantScoped`, it throws

```
java.lang.IllegalStateException: Scope Not Active
	at org.tomitribe.microscoped.core.ScopeContext$1.get(ScopeContext.java:126)
	at org.tomitribe.microscoped.core.ScopeContext.get(ScopeContext.java:101)
	at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.getIfExists(ContextualInstanceStrategy.java:90)
	at org.jboss.weld.bean.ContextualInstance.getIfExists(ContextualInstance.java:63)
	at org.jboss.weld.bean.proxy.ContextBeanInstance.getInstance(ContextBeanInstance.java:83)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.getInstance(ProxyMethodHandler.java:125)
```

**Comment by heruan** [comment]
Seems like it was not a EAR/WAR or BeanManager issue, but simple a threading issue (some threads didn't activate the scope).
